export const ADD_ARTICLE_STARTED = "ADD_ARTICLE_STARTED";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const REMOTE_ARTICLE_FAILURE = "REMOTE_ARTICLE_FAILURE";
export const DATA_FETCH_START = "DATA_FETCH_START"
export const DATA_LOADED = "DATA_LOADED";